name = "SYMPANpack"
author = "Team Elrant"
version = "1.6.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a45c258328c22f3268e08082661bb18e72597497cf2bb486bc434d33ffed0332"

[versions]
minecraft = "1.19.3"
quilt = "0.18.10"
