enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 384
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 12.0
leavesCullingMode = "CHECK"
leavesCullingAmount = 2
includeMangroveRoots = true
powderSnowCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
seasonsextras = true
farmersdelight = true
milk = true
create = true
charm = true
minecraft = true
